spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.108.128:3306/gulimall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.108.128:8848
#    alicloud:
#      access-key: LTAI5tKrrx19UTQ5PKuGfR1V
#      secret-key: u0CzCIWlKyds0GuJsvw6RMQrHaqUzt
#      oss:
#        endpoint: oss-cn-hangzhou.aliyuncs.com

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: gulimall-product


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 10001

logging:
  level:
    com.atguigu.gulimall: debug

